name: Get BigQuery Download Stats

on:
  workflow_dispatch:

jobs:
  query:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (shallow)
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Only checkout the latest commit to speed things up
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-cloud-bigquery pandas

      - name: Run BigQuery query
        env:
          GOOGLE_APPLICATION_CREDENTIALS_CONTENT: ${{ secrets.GCP_CREDENTIALS }}
        run: python misc/bigquery_query.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: bigquery-stats
          path: misc/bigquery_download_stats.csv
