name: Get BigQuery Download Stats

on:
  schedule:
    - cron: '0 7 * * *'  # Runs at 7 AM UTC, which is 2 AM EST
  workflow_dispatch:  # Allows manual triggering

jobs:
  query:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (shallow)
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Only checkout the latest commit to speed things up

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-cloud-bigquery pandas

      - name: Run BigQuery query
        env:
          GOOGLE_APPLICATION_CREDENTIALS_CONTENT: ${{ secrets.GCP_CREDENTIALS }}
        run: python misc/bigquery_download_stats.py

      - name: Configure Git user
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit and push only CSV to 'download_stats' branch
        run: |
          # Create a new branch for the download stats
          git checkout -b download_stats

          # Remove all files except the CSV file
          find . -type f ! -name 'bigquery_download_stats.csv' -exec rm -f {} \;

          # Add only the CSV file
          git add bigquery_download_stats.csv

          # Commit the change
          git commit -m "Add BigQuery download stats CSV"

          # Push the changes to the 'download_stats' branch
          git push origin download_stats

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Used for pushing changes to the repo

      - name: Disable triggering other workflows
        run: |
          echo "No workflows will be triggered on this branch."
