name: Format code

on:
  push:
    branches: [master]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: clonedSemicolon/setup-strace@v13
    - name: Format code with black
      run: |
        pip install black isort
        cd simba
        isort .
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: ${{ github.actor }}
        author_email: ${{ github.actor }}@users.noreply.github.com
        message: "cleaned"
        add: "."
        branch: ${{ github.ref }}
    - name: Upload strace artifacts
      uses: actions/upload-artifact@v4
      with:
        name: strace-logs-${{ github.job }}-${{ matrix.flavor || 'lint' }}-${{ github.run_id }}-${{ github.run_attempt }}-${{ strategy.job-index || 0 }}
        path: /home/runner/strace_logs/
