name: Daily GitHub Issue Report

on:
  schedule:
    - cron: '30 6 * * *'  # Cron time in UTC (6:30 AM UTC)
  workflow_dispatch:  # Allows manual trigger

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: 'download_stats'  # Checkout the download_stats branch

    - name: Verify current branch
      run: |
        git branch

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests  # Install required dependencies

    - name: List files in the repository
      run: |
        ls -R /home/runner/work/simba/simba/

    - name: Fetch GitHub issues and generate report
      run: |
        python /home/runner/work/simba/simba/scripts/create_issues_report.py  # Ensure the path is correct

    - name: Commit CSV file to download_stats branch
      run: |
        mkdir -p misc  # Create misc directory if it doesn't exist

        # Overwrite the existing CSV report in misc directory
        mv -f /home/runner/work/simba/simba/misc/github_issues_report.csv misc/github_issues_report.csv

        # Configure Git with authentication using GITHUB_TOKEN
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        
        # Use the built-in GITHUB_TOKEN for authentication
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

        # Add, commit, and push changes
        git add misc/github_issues_report.csv
        git commit -m "Update daily issues report"
        git push origin download_stats  # Push changes to the download_stats branch
